# Generated by Django 5.1.7 on 2025-03-12 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_is_deleted_blog_is_published_comment_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='is_deleted',
        ),
    ]
