# Generated by Django 5.1.7 on 2025-03-12 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_tag_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
